require('./gulp/tasks/styles');
require('./gulp/tasks/scripts');
require('./gulp/tasks/watch');
require('./gulp/tasks/modernizr');
require('./gulp/tasks/images');
require('./gulp/tasks/copy_super');
require('./gulp/tasks/clean');
require('./gulp/tasks/zip');
require('./gulp/tasks/default');
